### ISSUE TITLE
프로젝트 열기 -> 프로젝트 생성 수정 요청

### ISSUE THREAD

**Issue by backend-sunho-lee** [psy2848048/ciceronAPI#1]
번역공구 API 중
POST /api/v2/admin/pretranslated/project
프로젝트 열기의 의미가 프로젝트 생성으로 쓰이고 있습니다. 혼란을 일으킵니다. 

수정부탁드려요~:)

**Comment by psy2848048** [comment]
완 ㅋ 료 ㅋ
